[project]
name = "cf-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "google-genai>=1.2.0",
    "jinja2>=3.1.5",
    "python-multipart>=0.0.20",
    "sqlalchemy>=2.0.38",
]
